@extends('layouts.chapter')
@section('title',$all?'Member dues recording':'My member dues')
@section('content')
<div class="page-heading"><div><div class="eyebrow">CHAPTER MEMBERSHIP</div><h1>{{ $all?'Member dues recording':'My member dues' }}</h1><p>{{ $all?'Assess monthly dues, record payments, and keep each collection linked to the ledger.':'Your official dues, payments, and receipts as recorded by the Treasurer.' }}</p></div></div>
@if($all)<details class="panel form-panel"><summary class="large-summary">Open / adjust a monthly dues period</summary><form method="POST" action="{{ route('dues.store') }}" class="form-grid">@csrf
<x-field name="period" label="Dues period" type="month" :value="now()->format('Y-m')" required/><x-field name="due_date" label="Due date" type="date" required/>
<x-field name="member_id" label="Member (leave blank for all active members)" type="select" :options="$members->pluck('name','id')->all()"/>
<x-field name="amount" label="Dues amount (PHP)" type="number" min="0" step="0.01" required/>
<x-field name="remarks" label="Policy / adjustment / waiver reason" type="textarea" required/><div class="full"><p class="hint">The chapter sets the amount and deadline each period. Enter zero with a reason to waive an unpaid assessment.</p><button class="btn primary">Save dues period</button></div></form></details>@endif
<section class="panel">@forelse($dues as $due)<details class="ledger-row"><summary><div class="row-main"><strong>{{ $all?$due->member?->name:'Monthly membership dues' }}</strong><small>{{ $due->period }} · Due {{ $due->due_date?->format('M d, Y') }}</small></div><span>₱{{ number_format($due->paid,2) }} / ₱{{ number_format($due->amount,2) }}</span><span class="badge">{{ $due->amount==0?'Waived / Adjusted':$due->status }}</span></summary><div class="ledger-details"><p>{{ $due->remarks }}</p><p>Outstanding balance: <strong>₱{{ number_format($due->balance,2) }}</strong></p>
<div class="table-wrap"><table><thead><tr><th>Reference</th><th>Date</th><th>Amount</th><th>Status</th><th>Receipt</th></tr></thead><tbody>@forelse($due->payments as $payment)<tr><td>{{ $payment->reference }}</td><td>{{ $payment->transaction_date?->format('M d, Y') }}</td><td>₱{{ number_format($payment->amount,2) }}</td><td>{{ $payment->status }}</td><td>@if($payment->document_path)<a class="text-link" href="{{ route('ledger.receipt',$payment) }}">Download ↓</a>@else—@endif</td></tr>@empty<tr><td colspan="5">No payments recorded.</td></tr>@endforelse</tbody></table></div>
@if($all && $due->balance>0)<form method="POST" action="{{ route('dues.payment',$due) }}" enctype="multipart/form-data" class="form-grid">@csrf<x-field name="reference" label="Payment reference" required/><x-field name="amount" label="Amount paid (PHP)" type="number" min="0.01" :max="$due->balance" step="0.01" required/><x-field name="transaction_date" label="Payment date" type="date" :value="now()->format('Y-m-d')" required/><x-field name="payment_method" label="Payment method" type="select" :options="array_combine(['Cash','Bank transfer','GCash','Cheque','Other'],['Cash','Bank transfer','GCash','Cheque','Other'])" value="Cash" required/><x-field name="remarks" label="Payment remarks" type="textarea"/><x-field name="receipt" label="Receipt / proof (PDF or image)" type="file"/><div class="full"><button class="btn primary">Record payment</button></div></form>@endif</div></details>@empty<div class="empty-state"><h3>No dues assessments yet.</h3><p>Dues periods and payments will appear here once recorded by the Treasurer.</p></div>@endforelse@include('chapter.partials.pagination',['items'=>$dues])</section>
@endsection
