@extends('layouts.chapter')
@section('title',request('filter')==='liquidation'?'Liquidation':'Treasurer ledger')
@section('content')
<div class="page-heading"><div><div class="eyebrow">OFFICIAL FINANCIAL RECORDS</div><h1>{{ request('filter')==='liquidation'?'Liquidation':'Treasurer ledger' }}</h1><p>Record receipts and disbursements. Preserve corrections through a documented void.</p></div><a class="btn secondary" href="{{ route('ledger.export') }}">Export CSV ↓</a></div>
<details class="panel form-panel no-print"><summary class="large-summary">＋ Record financial transaction</summary><form method="POST" action="{{ route('ledger.store') }}" enctype="multipart/form-data" class="form-grid">@csrf
<x-field name="reference" label="Unique transaction reference" required/><x-field name="transaction_date" label="Transaction date" type="date" :value="now()->format('Y-m-d')" required/>
<x-field name="type" label="Transaction type" type="select" :options="array_combine(['Income','Expense','Disbursement','Adjustment credit','Adjustment debit'],['Income','Expense','Disbursement','Adjustment credit','Adjustment debit'])" required/>
<x-field name="project_id" label="Project (optional for chapter transactions)" type="select" :options="$projects->pluck('title','id')->all()"/>
<x-field name="member_id" label="Related member (optional)" type="select" :options="$members->pluck('name','id')->all()"/>
<x-field name="amount" label="Amount (PHP)" type="number" step="0.01" min="0.01" required/>
<x-field name="category" label="Category" required/><x-field name="account" label="Account / fund" value="Chapter fund" required/>
<x-field name="counterparty" label="Payee / payer" required/><x-field name="payment_method" label="Payment method" type="select" :options="array_combine(['Cash','Bank transfer','GCash','Cheque','Other'],['Cash','Bank transfer','GCash','Cheque','Other'])" value="Cash" required/>
<x-field name="description" label="Description" type="textarea" required/><x-field name="remarks" label="Remarks / adjustment explanation" type="textarea"/>
<x-field name="receipt" label="Receipt / supporting document (PDF or image, max 10 MB)" type="file"/>
<div class="full"><div class="notice">Record dues payments in Member Dues to keep the monthly dues record linked to the ledger. Expenses may not exceed the project's available allocation.</div><button class="btn primary">Post transaction</button></div></form></details>
<section class="panel"><div class="panel-heading"><h2>{{ request('filter')==='liquidation'?'Disbursements & liquidation':'Transaction history' }}</h2><a class="text-link" href="{{ route('dues.manage') }}">Record member dues →</a></div>
@forelse($entries as $entry)<details class="ledger-row"><summary><div><strong>{{ $entry->reference }}</strong><small>{{ $entry->transaction_date?->format('M d, Y') }} · {{ $entry->type }}</small></div><div class="row-main"><strong>{{ $entry->description }}</strong><small>{{ $entry->project?->title??$entry->member?->name??'Chapter transaction' }}</small></div><strong class="{{ $entry->direction==='credit'?'positive':'money' }}">{{ $entry->direction==='credit'?'+':'−' }} ₱{{ number_format($entry->amount,2) }}</strong><span class="badge">{{ $entry->status }}</span></summary>
<div class="ledger-details"><div class="detail-grid"><div><h3>Payee / payer</h3><p>{{ $entry->counterparty }}</p></div><div><h3>Account / category</h3><p>{{ $entry->account }} · {{ $entry->category }}</p></div><div><h3>Payment method</h3><p>{{ $entry->payment_method }}</p></div><div><h3>Liquidation</h3><p>{{ $entry->liquidation_status }}</p></div></div><p>{{ $entry->remarks }}</p>@if($entry->void_reason)<p class="danger-text">Void reason: {{ $entry->void_reason }}</p>@endif
@if($entry->document_path)<a class="btn secondary" href="{{ route('ledger.receipt',$entry) }}">Download supporting document ↓</a>@endif
@if($entry->status==='Posted')<form class="form-grid no-print" method="POST" action="{{ route('ledger.update',$entry) }}" enctype="multipart/form-data">@csrf<x-field name="action" label="Record action" type="select" :options="$entry->direction==='debit'?['liquidate'=>'Confirm liquidation','void'=>'Void transaction']:['void'=>'Void transaction']" required/><x-field name="remarks" label="Reason / liquidation remarks" type="textarea" required/><x-field name="receipt" label="Receipt / supporting document" type="file"/><div class="full"><button class="btn secondary" data-confirm="Record this financial change? The previous values will remain in the audit trail.">Save financial action</button></div></form>@endif</div></details>
@empty<div class="empty-state"><h3>No financial transactions recorded.</h3><p>Posted income, expenses, disbursements, and dues payments will appear here.</p></div>@endforelse
@include('chapter.partials.pagination',['items'=>$entries])</section>
@endsection
