@extends('layouts.chapter')
@section('title',request('filter')==='concepts'?'Project concepts':'Projects')
@section('content')
<div class="page-heading"><div><div class="eyebrow">FROM IDEA TO IMPACT</div><h1>{{ request('filter')==='concepts'?'Project concepts':'Projects' }}</h1><p>Plan, review, and follow the work that moves our community forward.</p></div><a class="btn primary" href="{{ route('projects.create') }}">＋ New project concept</a></div>
<div class="filter-tabs">@foreach([''=>'All projects','mine'=>'My projects','concepts'=>'Concepts','review'=>'Pending review','Approved'=>'Approved','Ongoing'=>'Ongoing','Completed'=>'Completed','Archived'=>'Archived'] as $value=>$label)<a class="{{ request('filter','')===$value?'selected':'' }}" href="{{ route('projects',['filter'=>$value]) }}">{{ $label }}</a>@endforeach</div>
<form class="search-bar" method="GET"><input type="hidden" name="filter" value="{{ request('filter') }}"><label class="sr-only" for="project-search">Search projects</label><input id="project-search" name="q" value="{{ request('q') }}" placeholder="Search by project title…"><button class="btn secondary">Search</button></form>
<div class="project-grid">@forelse($projects as $project)<article class="project-card"><div class="card-top"><span class="eyebrow">{{ $project->reference }}</span><span class="badge">{{ $project->status }}</span></div><p class="area-label">{{ $project->area }}</p><h2><a href="{{ route('projects.show',$project) }}">{{ $project->title }}</a></h2><p class="project-summary">{{ \Illuminate\Support\Str::limit($project->concept['objective']??'',120) }}</p><div class="project-meta"><span>Chair <strong>{{ $project->chair?->name ?? 'Not assigned' }}</strong></span><span>Date <strong>{{ $project->starts_on?->format('M d, Y') ?? 'To be set' }}</strong></span></div><div class="progress-label"><span>Task completion</span><strong>{{ $project->progress }}%</strong></div><progress value="{{ $project->progress }}" max="100"></progress><div class="card-bottom"><span>Allocation <strong>₱{{ number_format($project->allocated,2) }}</strong></span><a class="text-link" href="{{ route('projects.show',$project) }}">Open project →</a></div></article>@empty<div class="panel empty-state full"><h2>No projects found.</h2><p>Create a concept letter or change your search filters.</p><a class="btn primary" href="{{ route('projects.create') }}">Create a concept</a></div>@endforelse</div>
@include('chapter.partials.pagination',['items'=>$projects])
@endsection

