@extends('layouts.chapter')
@section('title',$kind==='letters'?'Partner letter':'Report')
@section('content')
<div class="page-heading"><div><a class="back-link" href="{{ route('records',$kind) }}">← {{ $kind==='letters'?'Partner letters':'Reports' }}</a><div class="eyebrow">{{ $record->type }} · VERSION {{ $record->version }}</div><h1>{{ $record->title }}</h1><p>Prepared by {{ $record->author?->name }} · {{ $record->updated_at->format('M d, Y H:i') }}</p></div><span class="badge large">{{ $record->status }}</span></div>
<div class="button-row no-print"><button class="btn secondary" type="button" data-print>Print / save PDF</button>
@if($editable)<a class="btn secondary" href="{{ route('records.edit',[$kind,$record->id]) }}">Edit draft</a><form method="POST" action="{{ route('records.transition',[$kind,$record->id]) }}">@csrf<input type="hidden" name="action" value="submit"><button class="btn primary">Submit to Admin</button></form>@endif
@if(isset($record->data['attachment_path']))<a class="btn secondary" href="{{ route('records.attachment',[$kind,$record->id]) }}">Download attachment ↓</a>@endif
@if(auth()->user()->role==='admin'&&in_array($record->status,['Submitted','For Review']))<form class="inline-review" method="POST" action="{{ route('records.transition',[$kind,$record->id]) }}">@csrf<x-field name="comments" label="Review comments" required/><button name="action" value="approve" class="btn primary">{{ $kind==='letters'?'Approve for Sending':'Mark Reviewed' }}</button><button name="action" value="return" class="btn secondary">Return for Revision</button></form>@endif
@php $manager=$record->project_id?$record->project->canManage(auth()->user()):auth()->user()->role==='treasurer'; @endphp
@if($manager && $kind==='letters'&&$record->status==='Approved for Sending')<form method="POST" action="{{ route('records.transition',[$kind,$record->id]) }}">@csrf<input type="hidden" name="action" value="sent"><button class="btn primary">Mark as Sent</button></form><span class="hint">Record this after sending the letter through your chapter's communication channel.</span>@endif
@if($manager&&in_array($record->status,['Reviewed','Sent','Approved for Sending']))<form method="POST" action="{{ route('records.transition',[$kind,$record->id]) }}">@csrf<input type="hidden" name="action" value="revise"><button class="btn secondary">Create a revision</button></form>@endif
@if($kind==='letters'&&$record->status==='Sent'&&($manager||auth()->user()->role==='admin'))<form method="POST" action="{{ route('records.transition',[$kind,$record->id]) }}">@csrf<input type="hidden" name="action" value="archive"><button class="btn secondary">Archive letter</button></form>@endif</div>
@if($record->review_comments)<div class="notice"><strong>Review comments:</strong> {{ $record->review_comments }}</div>@endif
<section class="panel form-panel printable-document"><div class="document-letterhead"><strong>JCI CARMONA</strong><span>Carmona City, Cavite, Philippines</span></div><h2>{{ $record->title }}</h2>
@if(isset($record->data['project_snapshot']))<div class="notice"><strong>{{ $record->data['project_snapshot']['reference'] }} · {{ $record->data['project_snapshot']['title'] }}</strong><p>{{ $record->data['project_snapshot']['description'] }}</p><span>{{ $record->data['project_snapshot']['date'] }} · {{ $record->data['project_snapshot']['venue'] }}</span></div>@endif
<div class="detail-grid">@foreach($kind==='letters'?\App\Support\ChapterForms::LETTER:($record->project_id?\App\Support\ChapterForms::REPORT:\App\Support\ChapterForms::FINANCIAL_REPORT) as $key=>$label)<div><h3>{{ $label }}</h3><p class="preserve-lines">{{ $record->data[$key]??'Not provided' }}</p></div>@endforeach</div>
@if($kind==='reports'&&isset($record->data['project_snapshot']))<h3 class="subheading">Project financial snapshot</h3><p>Allocated: ₱{{ number_format($record->data['project_snapshot']['allocated'],2) }} · Actual expenses: ₱{{ number_format($record->data['project_snapshot']['expenses'],2) }} · Remaining: ₱{{ number_format($record->data['project_snapshot']['remaining'],2) }}</p>@endif
@if(isset($record->data['financial_snapshot']))@php $snapshot=$record->data['financial_snapshot']; @endphp<h3 class="subheading">Official ledger snapshot at submission</h3><p>Income: ₱{{ number_format($snapshot['income'],2) }} · Expenses: ₱{{ number_format($snapshot['expenses'],2) }} · Net movement: ₱{{ number_format($snapshot['income']-$snapshot['expenses'],2) }}</p><div class="table-wrap"><table><thead><tr><th>Reference</th><th>Type</th><th>Description</th><th>Direction</th><th>Amount</th></tr></thead><tbody>@foreach($snapshot['transactions'] as $entry)<tr><td>{{ $entry['reference'] }}</td><td>{{ $entry['type'] }}</td><td>{{ $entry['description'] }}</td><td>{{ $entry['direction'] }}</td><td>₱{{ number_format($entry['amount'],2) }}</td></tr>@endforeach</tbody></table></div><small>Captured {{ $snapshot['captured_at'] }}. Later corrections do not rewrite this submission.</small>@endif
</section>
@if($record->versions)<section class="panel form-panel"><h2>Previous versions</h2>@foreach(array_reverse($record->versions) as $version)<details class="record-detail"><summary><strong>Version {{ $version['version'] }} · {{ $version['status'] }}</strong><span>{{ $version['saved_at'] }}</span></summary><h3>{{ $version['title'] }}</h3>@foreach($version['data'] as $key=>$value)@if(!str_contains($key,'path'))<div><h4>{{ ucwords(str_replace('_',' ',$key)) }}</h4><p class="preserve-lines">{{ is_array($value)?json_encode($value,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE):$value }}</p></div>@endif @endforeach</details>@endforeach</section>@endif
@endsection
